DROP TABLE IF EXISTS answers CASCADE;
CREATE TABLE answers (
  id SERIAL PRIMARY KEY NOT NULL,
  answer TEXT,
  timer  NUMERIC,
  questionId INTEGER NOT NULL REFERENCES questions(id) ON DELETE CASCADE
);